### ISSUE TITLE
How to use this with Flask, Django or Channels

### ISSUE THREAD

**Issue by cjds** [pyros-dev/pyros-setup#47]
Is there any tutorial about how to use pyros with any of these system. This is mentioned in your description as part of the functionality, but I can't figure out how to use it

**Comment by asmodehn** [comment]
Not sure what is the goal here, what it is we would be trying to achieve...
[Rostful](https://github.com/pyros-dev/rostful) use [pyros](https://github.com/pyros-dev) framework to interface flask with ROS.
pyros-setup is just a tiny piece of it that makes importing ros modules easier than it is by default. And to use it you just need one line of code (see readme)

**Comment by asmodehn** [comment]
If there isn't anything else regarding this issue, I assume we can close it ?
