### ISSUE TITLE
Melodic ?

### ISSUE THREAD

**Issue by asmodehn** [pyros-dev/pyros-setup#66]
Because Time is moving on : http://wiki.ros.org/Distributions

**Comment by alankritapathak** [comment]
+1 
Is there any progress on this ?

**Comment by asmodehn** [comment]
Hello,
The change has been done in #65
I have been waiting to merge that PR because of : https://github.com/direnv/direnv/issues/501
It would be good if you could review that branch and let me know if everything works for you, thanks !

**Comment by alankritapathak** [comment]
Thanks, I tested this branch and everything works for me. It will be great if you can merge it to master

**Comment by asmodehn** [comment]
OK I ll do that soon then. Thanks !
